# -*- coding: utf-8 -*-
"""mini_project_Real_Time_Log_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/adityachoudhary24/real-time-log-processing-spark/blob/main/mini_project_Real_Time_Log_processing.ipynb

Step 1 – Install and Import Libraries
"""

!pip install pyspark

import pandas as pd
import random
import time
from datetime import datetime
from pyspark.sql import SparkSession

"""Step 2 – Create Spark Session"""

spark = SparkSession.builder.appName("RealTimeLogProcessing").getOrCreate()

"""Step 3 – Create Log Data Generator"""

# Step 3 - Create Improved Log Data Generator

pages = [
    "/",
    "/products",
    "/cart",
    "/checkout",
    "/login",
    "/contact"
]

status_codes = [
    200, 200, 200, 200,
    201,
    400,
    404,
    500
]

def generate_log():

    return {
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "ip_address": f"192.168.1.{random.randint(1, 254)}",
        "endpoint": random.choice(pages),
        "status_code": random.choice(status_codes),
        "response_time_ms": random.randint(50, 1500)
    }

"""Step 4 – Simulate Streaming Log Data"""

## Step 4 - Generate Log Data

logs = []

for i in range(100):

    log = generate_log()

    logs.append(log)

    print("New Log:", log)

    time.sleep(0.1)

# Step 5 - Create Pandas DataFrame

logs_df = pd.DataFrame(logs)

logs_df.head()

# Step 6 - Create PySpark DataFrame

spark_df = spark.createDataFrame(logs)

spark_df.show(10)

# Step 7 - Basic Request Analytics

from pyspark.sql.functions import count, when, col

total_requests = spark_df.count()

successful_requests = spark_df.filter(
    col("status_code").isin(200, 201)
).count()

error_requests = spark_df.filter(
    col("status_code") >= 400
).count()

error_rate = (error_requests / total_requests) * 100

print("Total Requests:", total_requests)
print("Successful Requests:", successful_requests)
print("Error Requests:", error_requests)
print("Error Rate:", round(error_rate, 2), "%")

# Step 8 - Requests by Endpoint

endpoint_requests = (
    spark_df
    .groupBy("endpoint")
    .count()
    .orderBy(col("count").desc())
)

endpoint_requests.show()

# Step 9 - Error Analysis by Endpoint

error_by_endpoint = (
    spark_df
    .filter(col("status_code") >= 400)
    .groupBy("endpoint")
    .count()
    .orderBy(col("count").desc())
)

error_by_endpoint.show()

# Step 10 - Status Code Analysis

status_analysis = (
    spark_df
    .groupBy("status_code")
    .count()
    .orderBy("status_code")
)

status_analysis.show()

# Step 11 - Response Time Analysis

from pyspark.sql.functions import avg, max, min

response_time_stats = spark_df.select(
    avg("response_time_ms").alias("average_response_time"),
    max("response_time_ms").alias("maximum_response_time"),
    min("response_time_ms").alias("minimum_response_time")
)

response_time_stats.show()

# Step 12 - Detect Slow Requests

slow_requests = (
    spark_df
    .filter(col("response_time_ms") > 1000)
    .orderBy(col("response_time_ms").desc())
)

slow_requests.show()

# Step 13 - Anomaly Detection

anomalies = (
    spark_df
    .filter(
        (col("response_time_ms") > 1000) |
        (col("status_code") == 500)
    )
    .orderBy(col("response_time_ms").desc())
)

anomalies.show()

# Step 14 - Count Detected Anomalies

anomaly_count = anomalies.count()

print("Total Anomalies Detected:", anomaly_count)

# Step 15 - Save Processed Logs

output_df = spark_df.toPandas()

output_df.to_csv("processed_logs.csv", index=False)

print("Processed logs saved successfully!")

# Step 16 - Save Detected Anomalies

anomalies.toPandas().to_csv("detected_anomalies.csv", index=False)

print("Anomaly results saved successfully!")

# Step 17 - Requests by Endpoint Visualization

import matplotlib.pyplot as plt

endpoint_data = (
    spark_df
    .groupBy("endpoint")
    .count()
    .orderBy(col("count").desc())
    .toPandas()
)

plt.figure(figsize=(8, 5))
plt.bar(endpoint_data["endpoint"], endpoint_data["count"])
plt.xlabel("Endpoint")
plt.ylabel("Number of Requests")
plt.title("Requests by Endpoint")
plt.xticks(rotation=45)
plt.show()

# Step 18 - HTTP Status Distribution

status_data = (
    spark_df
    .groupBy("status_code")
    .count()
    .orderBy("status_code")
    .toPandas()
)

plt.figure(figsize=(8, 5))
plt.bar(
    status_data["status_code"].astype(str),
    status_data["count"]
)
plt.xlabel("HTTP Status Code")
plt.ylabel("Number of Requests")
plt.title("HTTP Status Code Distribution")
plt.show()

# Step 19 - Response Time Distribution

response_data = spark_df.select(
    "response_time_ms"
).toPandas()

plt.figure(figsize=(8, 5))
plt.hist(response_data["response_time_ms"], bins=10)
plt.xlabel("Response Time (ms)")
plt.ylabel("Number of Requests")
plt.title("Response Time Distribution")
plt.show()

# Step 20 - Explain Anomalies

from pyspark.sql.functions import when

anomalies_with_reason = (
    spark_df
    .filter(
        (col("response_time_ms") > 1000) |
        (col("status_code") == 500)
    )
    .withColumn(
        "anomaly_reason",
        when(
            (col("response_time_ms") > 1000) &
            (col("status_code") == 500),
            "Slow response + Server error"
        )
        .when(
            col("response_time_ms") > 1000,
            "Slow response"
        )
        .when(
            col("status_code") == 500,
            "Server error"
        )
    )
)

anomalies_with_reason.show()

# Step 21 - Save Anomaly Report

anomalies_with_reason.toPandas().to_csv(
    "detected_anomalies.csv",
    index=False
)

print("Anomaly report saved successfully!")

# Step 22 - Prepare Dashboard Data

dashboard_df = spark_df.toPandas()

dashboard_df.head()

!pip install streamlit -q

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# 
# st.set_page_config(
#     page_title="Real-Time Log Analytics",
#     layout="wide"
# )
# 
# st.title("Real-Time Log Analytics Dashboard")
# 
# # Load processed logs
# df = pd.read_csv("processed_logs.csv")
# 
# # Basic metrics
# total_requests = len(df)
# successful_requests = len(df[df["status_code"].isin([200, 201])])
# error_requests = len(df[df["status_code"] >= 400])
# error_rate = (error_requests / total_requests) * 100
# 
# # Metrics
# col1, col2, col3, col4 = st.columns(4)
# 
# col1.metric("Total Requests", total_requests)
# col2.metric("Successful Requests", successful_requests)
# col3.metric("Error Requests", error_requests)
# col4.metric("Error Rate", f"{error_rate:.2f}%")
# 
# st.subheader("Requests by Endpoint")
# 
# endpoint_counts = df["endpoint"].value_counts()
# 
# st.bar_chart(endpoint_counts)
# 
# st.subheader("HTTP Status Code Distribution")
# 
# status_counts = df["status_code"].value_counts().sort_index()
# 
# st.bar_chart(status_counts)
# 
# st.subheader("Response Time Analysis")
# 
# st.write(
#     f"Average Response Time: {df['response_time_ms'].mean():.2f} ms"
# )
# 
# st.write(
#     f"Maximum Response Time: {df['response_time_ms'].max()} ms"
# )
# 
# st.subheader("Detected Anomalies")
# 
# anomalies = df[
#     (df["response_time_ms"] > 1000) |
#     (df["status_code"] == 500)
# ]
# 
# st.dataframe(anomalies)

!ls -l app.py processed_logs.csv detected_anomalies.csv

!pip install pyngrok -q